In [1]:
import numpy as np

In [8]:
#1
print("Creating 5X2 array using np.arange")
sampleArray = np.arange(0, 100, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using np.arange
[[ 0 10]
 [20 30]
 [40 50]
 [60 70]
 [80 90]]


In [9]:
#2
print("Creating 8X3 array using np.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(sampleArray, 4) 
print(subArrays)

Creating 8X3 array using np.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [10]:
#3
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

minOfAxisOne = np.amin(sampleArray, 1) 
print("Printing amin Of Axis 1")
print(minOfAxisOne)

maxOfAxisOne = np.amax(sampleArray, 0) 
print("Printing amax Of Axis 0")
print(maxOfAxisOne)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing amin Of Axis 1
[34 12 53]
Printing amax Of Axis 0
[82 94 73]


In [11]:
#4
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [12]:
#5
l = [1, 2, 3, 4]
res = [pow(i, 3) for i in l] # Cube List using list comprehension
print(res)


[1, 8, 27, 64]


In [16]:
#6 
def main():
    d = {'A' : [1, 2, 3, 4, 5, 6, 7, 8, 9],'B' : 34,'C' : 12,'D' : [7, 8, 9, 6, 4] }
    print(sum([len(d[x]) for x in d if isinstance(d[x], list)])) # using list comprehension
if __name__ == '__main__':
    main()


14


In [18]:
#7
my_dict = {'x':50, 'y':58, 'z': 56}
key_max = max(my_dict.keys(), key=(lambda k: my_dict[k]))
key_min = min(my_dict.keys(), key=(lambda k: my_dict[k]))
print('Maximum Value: ',my_dict[key_max])
print('Minimum Value: ',my_dict[key_min])


Maximum Value:  58
Minimum Value:  50


In [19]:
#8
def returnSum(dict):
    return sum(dict.values())
dict = {'a': 100, 'b': 200, 'c': 300}
print("Sum :", returnSum(dict))

Sum : 600


In [20]:
#9
np.random.rand(3,2)

array([[0.98697131, 0.83245582],
       [0.78576939, 0.89684405],
       [0.26310109, 0.4412369 ]])

In [21]:
#10
array = np.arange(10)
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)

r2 = np.median(array)
print("\nMedian: ", r2)

r3 = np.std(array)
print("\nstd: ", r3)
  
r4 = np.var(array)
print("\nvariance: ", r4)

[0 1 2 3 4 5 6 7 8 9]

Mean:  4.5

Median:  4.5

std:  2.8722813232690143

variance:  8.25
